@startuml

package "User Interface" {
  [Web Application]
  [Android Application]
}

package "On-Prem Kubernetes" {
  [nginx]
  [Keycloak]
  [Hashicorp Vault]
  [localmovie-media-manager]
  [Prometheus]
  [Grafana]
  database "Postgresql" {
    [LocalMovies DB]
    [Keycloak DB]
    [Hashicorp Vault DB]
  }
}

cloud {
  [CloudFlare]
}

cloud "Notifications" {
  [Firebase]
  [APNs]
}

[Web Application] --> [CloudFlare]
[Web Application] -[hidden]down-> [nginx]
[Android Application] --> [CloudFlare]
[Android Application] -[hidden]down-> [nginx]


[CloudFlare] -down-> [nginx]

[nginx] --> [Keycloak] : Authentication/\nAuthorization
[nginx] --> [localmovie-media-manager]
[nginx] --> [Hashicorp Vault] : Manage/\nQuery Secrets
[nginx] --> [Grafana]

[localmovie-media-manager] --> [Firebase]
[localmovie-media-manager] --> [APNs]
[Firebase] --> [Android Application]
[APNs] --> [Android Application]

[localmovie-media-manager] -up-> [CloudFlare]

[localmovie-media-manager] --> [LocalMovies DB]
[Keycloak] --> [Keycloak DB]
[Hashicorp Vault] --> [Hashicorp Vault DB]

[Prometheus] --> [localmovie-media-manager]
[Grafana] --> [Prometheus]

@enduml