@startuml

legend top right
|= |= Use Case |
|<back:#FF0000>   </back>| View/Stream Media |
|<back:#00FF00>   </back>| Authentication/Authorization |
|<back:blue>   </back>| Monitoring |
|<back:orange>   </back>| Notifications |
|<back:grey>   </back>| Secret Management |
endlegend

rectangle "User Interface" {
  [Browser]
  [Android Application]
}

rectangle "On-Prem Kubernetes" {
  [nginx]
  [Keycloak]#00FF00
  [Hashicorp Vault]#grey
  [localmovie-media-manager]#red
  [Prometheus]#Blue
  [Grafana]#Blue
  database "Postgresql" {
  }
}

rectangle "NAS" {
 [Postgresql Data]
 [Media Files]
}

cloud {
  [CloudFlare]
  [Firebase]#Orange
}

[Browser] --[#Red]> [CloudFlare]
[Browser] --[#blue]> [CloudFlare]
[Browser] --[#grey]> [CloudFlare]
[Browser] --[#00FF00]> [CloudFlare]
[Browser] --[hidden]down-> [nginx]
[Android Application] -[#Red]down-> [CloudFlare]
[Android Application] -[hidden]down-> [nginx]

[CloudFlare] --[#Red]> [nginx]
[CloudFlare] --[#grey]> [nginx]
[CloudFlare] --[#00FF00]> [nginx]
[CloudFlare] --[#blue]> [nginx]

[nginx] --[#00FF00]> [Keycloak]
[nginx] --[#Red]> [localmovie-media-manager]
[nginx] --[#grey]> [Hashicorp Vault]
[nginx] -[#Blue]right-> [Grafana]

[localmovie-media-manager] --[#Orange]> Firebase
Firebase --[#Orange]> [Android Application]

[localmovie-media-manager] --[#Red]> [Media Files]
[localmovie-media-manager] --[#Grey]> [CloudFlare]
[localmovie-media-manager] --[#00FF00]> [CloudFlare]

[localmovie-media-manager] --[#Red]> Postgresql
[Keycloak] -[#00FF00]-> Postgresql
[Hashicorp Vault] --[#grey]> Postgresql

[Prometheus] -[#Blue]-> [localmovie-media-manager]
[Grafana] -[#Blue]-> [Prometheus]

Postgresql --> [Postgresql Data]

@enduml