apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: localmovies-cluster-role-binding
subjects:
  - kind: ServiceAccount
    name: localmovies
    namespace: localmovies
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: localmovies-cluster-role