ALTER TABLE if EXISTS media ADD COLUMN version BIGINT DEFAULT 0;
ALTER TABLE if EXISTS media_file_event ADD COLUMN version BIGINT DEFAULT 0;
ALTER TABLE if EXISTS media_image ADD COLUMN version BIGINT DEFAULT 0;
ALTER TABLE if EXISTS media_job ADD COLUMN version BIGINT DEFAULT 0;
ALTER TABLE if EXISTS media_user ADD COLUMN version BIGINT DEFAULT 0;
ALTER TABLE if EXISTS media_view ADD COLUMN version BIGINT DEFAULT 0;